// Generated by gencpp from file robot_transport/TransportRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_TRANSPORT_MESSAGE_TRANSPORTREQUEST_H
#define ROBOT_TRANSPORT_MESSAGE_TRANSPORTREQUEST_H

#include <ros/service_traits.h>


#include <robot_transport/TransportRequestRequest.h>
#include <robot_transport/TransportRequestResponse.h>


namespace robot_transport
{

struct TransportRequest
{

typedef TransportRequestRequest Request;
typedef TransportRequestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TransportRequest
} // namespace robot_transport


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_transport::TransportRequest > {
  static const char* value()
  {
    return "e41a7a3cc3ea192648ce06af33a5d757";
  }

  static const char* value(const ::robot_transport::TransportRequest&) { return value(); }
};

template<>
struct DataType< ::robot_transport::TransportRequest > {
  static const char* value()
  {
    return "robot_transport/TransportRequest";
  }

  static const char* value(const ::robot_transport::TransportRequest&) { return value(); }
};


// service_traits::MD5Sum< ::robot_transport::TransportRequestRequest> should match
// service_traits::MD5Sum< ::robot_transport::TransportRequest >
template<>
struct MD5Sum< ::robot_transport::TransportRequestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_transport::TransportRequest >::value();
  }
  static const char* value(const ::robot_transport::TransportRequestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_transport::TransportRequestRequest> should match
// service_traits::DataType< ::robot_transport::TransportRequest >
template<>
struct DataType< ::robot_transport::TransportRequestRequest>
{
  static const char* value()
  {
    return DataType< ::robot_transport::TransportRequest >::value();
  }
  static const char* value(const ::robot_transport::TransportRequestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_transport::TransportRequestResponse> should match
// service_traits::MD5Sum< ::robot_transport::TransportRequest >
template<>
struct MD5Sum< ::robot_transport::TransportRequestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_transport::TransportRequest >::value();
  }
  static const char* value(const ::robot_transport::TransportRequestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_transport::TransportRequestResponse> should match
// service_traits::DataType< ::robot_transport::TransportRequest >
template<>
struct DataType< ::robot_transport::TransportRequestResponse>
{
  static const char* value()
  {
    return DataType< ::robot_transport::TransportRequest >::value();
  }
  static const char* value(const ::robot_transport::TransportRequestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_TRANSPORT_MESSAGE_TRANSPORTREQUEST_H
