// Generated by gencpp from file robot_transport/TransportRequestRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_TRANSPORT_MESSAGE_TRANSPORTREQUESTREQUEST_H
#define ROBOT_TRANSPORT_MESSAGE_TRANSPORTREQUESTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_transport
{
template <class ContainerAllocator>
struct TransportRequestRequest_
{
  typedef TransportRequestRequest_<ContainerAllocator> Type;

  TransportRequestRequest_()
    : target()  {
    }
  TransportRequestRequest_(const ContainerAllocator& _alloc)
    : target(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _target_type;
  _target_type target;





  typedef boost::shared_ptr< ::robot_transport::TransportRequestRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_transport::TransportRequestRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TransportRequestRequest_

typedef ::robot_transport::TransportRequestRequest_<std::allocator<void> > TransportRequestRequest;

typedef boost::shared_ptr< ::robot_transport::TransportRequestRequest > TransportRequestRequestPtr;
typedef boost::shared_ptr< ::robot_transport::TransportRequestRequest const> TransportRequestRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_transport::TransportRequestRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_transport::TransportRequestRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_transport::TransportRequestRequest_<ContainerAllocator1> & lhs, const ::robot_transport::TransportRequestRequest_<ContainerAllocator2> & rhs)
{
  return lhs.target == rhs.target;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_transport::TransportRequestRequest_<ContainerAllocator1> & lhs, const ::robot_transport::TransportRequestRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_transport

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_transport::TransportRequestRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_transport::TransportRequestRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_transport::TransportRequestRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_transport::TransportRequestRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_transport::TransportRequestRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_transport::TransportRequestRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_transport::TransportRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "10e5cb524446adda5ea1765c6838590d";
  }

  static const char* value(const ::robot_transport::TransportRequestRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x10e5cb524446addaULL;
  static const uint64_t static_value2 = 0x5ea1765c6838590dULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_transport::TransportRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_transport/TransportRequestRequest";
  }

  static const char* value(const ::robot_transport::TransportRequestRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_transport::TransportRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string target  # 请求参数：目标标记（A/B/C/D/CAMP/WAIT）\n"
;
  }

  static const char* value(const ::robot_transport::TransportRequestRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_transport::TransportRequestRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TransportRequestRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_transport::TransportRequestRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_transport::TransportRequestRequest_<ContainerAllocator>& v)
  {
    s << indent << "target: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.target);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_TRANSPORT_MESSAGE_TRANSPORTREQUESTREQUEST_H
