// Generated by gencpp from file robot/TransportRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_MESSAGE_TRANSPORTREQUEST_H
#define ROBOT_MESSAGE_TRANSPORTREQUEST_H

#include <ros/service_traits.h>


#include <robot/TransportRequestRequest.h>
#include <robot/TransportRequestResponse.h>


namespace robot
{

struct TransportRequest
{

typedef TransportRequestRequest Request;
typedef TransportRequestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TransportRequest
} // namespace robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot::TransportRequest > {
  static const char* value()
  {
    return "e41a7a3cc3ea192648ce06af33a5d757";
  }

  static const char* value(const ::robot::TransportRequest&) { return value(); }
};

template<>
struct DataType< ::robot::TransportRequest > {
  static const char* value()
  {
    return "robot/TransportRequest";
  }

  static const char* value(const ::robot::TransportRequest&) { return value(); }
};


// service_traits::MD5Sum< ::robot::TransportRequestRequest> should match
// service_traits::MD5Sum< ::robot::TransportRequest >
template<>
struct MD5Sum< ::robot::TransportRequestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot::TransportRequest >::value();
  }
  static const char* value(const ::robot::TransportRequestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot::TransportRequestRequest> should match
// service_traits::DataType< ::robot::TransportRequest >
template<>
struct DataType< ::robot::TransportRequestRequest>
{
  static const char* value()
  {
    return DataType< ::robot::TransportRequest >::value();
  }
  static const char* value(const ::robot::TransportRequestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot::TransportRequestResponse> should match
// service_traits::MD5Sum< ::robot::TransportRequest >
template<>
struct MD5Sum< ::robot::TransportRequestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot::TransportRequest >::value();
  }
  static const char* value(const ::robot::TransportRequestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot::TransportRequestResponse> should match
// service_traits::DataType< ::robot::TransportRequest >
template<>
struct DataType< ::robot::TransportRequestResponse>
{
  static const char* value()
  {
    return DataType< ::robot::TransportRequest >::value();
  }
  static const char* value(const ::robot::TransportRequestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MESSAGE_TRANSPORTREQUEST_H
