// Generated by gencpp from file transport/TransportRequestResponse.msg
// DO NOT EDIT!


#ifndef TRANSPORT_MESSAGE_TRANSPORTREQUESTRESPONSE_H
#define TRANSPORT_MESSAGE_TRANSPORTREQUESTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace transport
{
template <class ContainerAllocator>
struct TransportRequestResponse_
{
  typedef TransportRequestResponse_<ContainerAllocator> Type;

  TransportRequestResponse_()
    : success(false)
    , message()  {
    }
  TransportRequestResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::transport::TransportRequestResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::transport::TransportRequestResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TransportRequestResponse_

typedef ::transport::TransportRequestResponse_<std::allocator<void> > TransportRequestResponse;

typedef boost::shared_ptr< ::transport::TransportRequestResponse > TransportRequestResponsePtr;
typedef boost::shared_ptr< ::transport::TransportRequestResponse const> TransportRequestResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::transport::TransportRequestResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::transport::TransportRequestResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::transport::TransportRequestResponse_<ContainerAllocator1> & lhs, const ::transport::TransportRequestResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::transport::TransportRequestResponse_<ContainerAllocator1> & lhs, const ::transport::TransportRequestResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace transport

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::transport::TransportRequestResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::transport::TransportRequestResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::transport::TransportRequestResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::transport::TransportRequestResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::transport::TransportRequestResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::transport::TransportRequestResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::transport::TransportRequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::transport::TransportRequestResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::transport::TransportRequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "transport/TransportRequestResponse";
  }

  static const char* value(const ::transport::TransportRequestResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::transport::TransportRequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success   # 响应结果：是否成功\n"
"string message # 响应消息：状态描述\n"
"\n"
"\n"
;
  }

  static const char* value(const ::transport::TransportRequestResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::transport::TransportRequestResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TransportRequestResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::transport::TransportRequestResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::transport::TransportRequestResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRANSPORT_MESSAGE_TRANSPORTREQUESTRESPONSE_H
