// Generated by gencpp from file transport/TransportRequest.msg
// DO NOT EDIT!


#ifndef TRANSPORT_MESSAGE_TRANSPORTREQUEST_H
#define TRANSPORT_MESSAGE_TRANSPORTREQUEST_H

#include <ros/service_traits.h>


#include <transport/TransportRequestRequest.h>
#include <transport/TransportRequestResponse.h>


namespace transport
{

struct TransportRequest
{

typedef TransportRequestRequest Request;
typedef TransportRequestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TransportRequest
} // namespace transport


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::transport::TransportRequest > {
  static const char* value()
  {
    return "e41a7a3cc3ea192648ce06af33a5d757";
  }

  static const char* value(const ::transport::TransportRequest&) { return value(); }
};

template<>
struct DataType< ::transport::TransportRequest > {
  static const char* value()
  {
    return "transport/TransportRequest";
  }

  static const char* value(const ::transport::TransportRequest&) { return value(); }
};


// service_traits::MD5Sum< ::transport::TransportRequestRequest> should match
// service_traits::MD5Sum< ::transport::TransportRequest >
template<>
struct MD5Sum< ::transport::TransportRequestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::transport::TransportRequest >::value();
  }
  static const char* value(const ::transport::TransportRequestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::transport::TransportRequestRequest> should match
// service_traits::DataType< ::transport::TransportRequest >
template<>
struct DataType< ::transport::TransportRequestRequest>
{
  static const char* value()
  {
    return DataType< ::transport::TransportRequest >::value();
  }
  static const char* value(const ::transport::TransportRequestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::transport::TransportRequestResponse> should match
// service_traits::MD5Sum< ::transport::TransportRequest >
template<>
struct MD5Sum< ::transport::TransportRequestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::transport::TransportRequest >::value();
  }
  static const char* value(const ::transport::TransportRequestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::transport::TransportRequestResponse> should match
// service_traits::DataType< ::transport::TransportRequest >
template<>
struct DataType< ::transport::TransportRequestResponse>
{
  static const char* value()
  {
    return DataType< ::transport::TransportRequest >::value();
  }
  static const char* value(const ::transport::TransportRequestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TRANSPORT_MESSAGE_TRANSPORTREQUEST_H
